### ISSUE TITLE
Reading sysmocom ISIM cards and is not working.

### ISSUE THREAD

**Issue by fasferraz** [mitshell/card#9]
I use this module in some applicatons i have done, and I was trying to use it with sysmocom ISIM, and when i try to select USIM application to read the IMSI or to do an authenticate operation, it fails:

root@ubuntu:/home/fabricio/Documents#python3
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from card.USIM import *
>>> a = USIM(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/card-0.3-py3.8.egg/card/USIM.py", line 195, in __init__
  File "/usr/local/lib/python3.8/dist-packages/card-0.3-py3.8.egg/card/USIM.py", line 205, in SELECT_ADF_USIM
  File "/usr/local/lib/python3.8/dist-packages/card-0.3-py3.8.egg/card/ICC.py", line 1244, in select
  File "/usr/local/lib/python3.8/dist-packages/card-0.3-py3.8.egg/card/ICC.py", line 1594, in parse_file
  File "/usr/local/lib/python3.8/dist-packages/card-0.3-py3.8.egg/card/ICC.py", line 728, in parse_file
  File "/usr/local/lib/python3.8/dist-packages/card-0.3-py3.8.egg/card/ICC.py", line 788, in parse_FCP
  File "/usr/local/lib/python3.8/dist-packages/card-0.3-py3.8.egg/card/ICC.py", line 940, in parse_compact_security_attribute
NameError: name 'self' is not defined

Using this slightly modified version https://github.com/sysmocom/sysmo-usim-tool/tree/master/card it works:

root@ubuntu:/home/fabricio/Documents# cd sysmo-usim-tool/
root@ubuntu:/home/fabricio/Documents/sysmo-usim-tool# python3
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from card.USIM import *
>>> a = USIM(0)
>>> a.get_imsi()
'901700000050900'
>>>

**Comment by mitshell** [comment]
I just pushed some little fixes and enhancement: I hope this to solve your error. Do a fresh checkout, retry and let me know how it goes.

**Comment by fasferraz** [comment]
Hi @mitshell 
Problem solved! 
Thanks!
